[".config/yazi/flavors"]
type = "archive"
url = "https://github.com/yazi-rs/flavors/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
include = ["*/catppuccin-latte.yazi/**", "*/catppuccin-macchiato.yazi/**"]

[".config/yazi/plugins/piper.yazi"]
type = "archive"
url = "https://github.com/yazi-rs/plugins/archive/master.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "168h"
include = ["*/piper.yazi/**"]

[".config/yazi/plugins/ouch.yazi"]
type = "archive"
url = "https://github.com/ndtoan96/ouch.yazi/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
