[tool_alias]
neovim = "asdf:richin13/asdf-neovim"
node = "asdf:asdf-vm/asdf-nodejs"
pipx = "asdf:yozachar/asdf-pipx"
python = "asdf:asdf-community/asdf-python"
ruby = "asdf:asdf-vm/asdf-ruby"

[tools]
bun = "latest"
go = "latest"
neovim = "nightly"
node = "latest"
pipx = "latest"
pnpm = "latest"
python = "3.12"
ruby = "latest"
rust = "latest"

"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:ast-grep/ast-grep" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:ClementTsang/bottom" = "latest"
"aqua:cli/cli" = "latest"
"aqua:gittower/git-flow-next" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:openziti/zrok" = "latest"
"aqua:ouch-org/ouch" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:sharkdp/vivid" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:twpayne/chezmoi" = "latest"
"aqua:veeso/termscp" = "latest"
"aqua:Wilfred/difftastic" = "latest"

"cargo:eza" = "latest"
"cargo:genact" = "latest"
"cargo:tokei" = "latest"

"github:matterhorn-chat/matterhorn" = "latest"
"github:zdyxry/tokui" = "latest"

"gitlab:gitlab-org/cli" = { version = "latest", exe = "glab" }

"npm:@aimuzov/sketchybar-app-font" = { version = "latest", exe = "sketchybar-app-font" }
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@georgesg/arc-cli" = { version = "latest", exe = "arc-cli" }
"npm:@modelcontextprotocol/server-everything" = "latest"
"npm:@modelcontextprotocol/server-filesystem" = "latest"
"npm:@modelcontextprotocol/server-memory" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"

"pipx:httpie" = "latest"
"pipx:mhinz/neovim-remote" = "latest"
"pipx:mcp-server-fetch" = "latest"
"pipx:mcp-server-git" = "latest"

"ubi:JanDeDobbeleer/oh-my-posh" = "latest"
"ubi:so-fancy/diff-so-fancy" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
