[tool_alias]
"core:neovim" = "asdf:richin13/asdf-neovim"
"core:node" = "asdf:asdf-vm/asdf-nodejs"
"core:pipx" = "asdf:yozachar/asdf-pipx"
"core:python" = "asdf:asdf-community/asdf-python"
"core:ruby" = "asdf:asdf-vm/asdf-ruby"

[tools]
"core:bun" = "latest"
"core:go" = "latest"
"core:neovim" = "nightly"
"core:node" = "latest"
"core:pipx" = "latest"
"core:pnpm" = "latest"
"core:python" = "3.12"
"core:ruby" = "latest"
"core:rust" = "latest"

"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:anomalyco/opencode" = "latest"
"aqua:ast-grep/ast-grep" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:ClementTsang/bottom" = "latest"
"aqua:cli/cli" = "latest"
"aqua:fish-shell/fish-shell" = "latest"
"aqua:github/copilot-cli" = "latest"
"aqua:gittower/git-flow-next" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:openziti/zrok" = "latest"
"aqua:ouch-org/ouch" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:sharkdp/vivid" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:twpayne/chezmoi" = "latest"
"aqua:veeso/termscp" = "latest"
"aqua:Wilfred/difftastic" = "latest"

"cargo:eza" = "latest"
"cargo:genact" = "latest"
"cargo:tokei" = "latest"

"github:matterhorn-chat/matterhorn" = "latest"
"github:zdyxry/tokui" = "latest"

"gitlab:gitlab-org/cli" = "latest"

"npm:@aimuzov/sketchybar-app-font" = "latest"
"npm:@eslint/mcp" = "latest"
"npm:@georgesg/arc-cli" = "latest"
"npm:@modelcontextprotocol/server-everything" = "latest"
"npm:@modelcontextprotocol/server-filesystem" = "latest"
"npm:@modelcontextprotocol/server-memory" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"
"npm:chrome-devtools-mcp" = "latest"

"pipx:httpie" = "latest"
"pipx:mcp-server-fetch" = "latest"
"pipx:mcp-server-git" = "latest"
"pipx:mhinz/neovim-remote" = "latest"
"pipx:yt-dlp" = "latest"

"ubi:JanDeDobbeleer/oh-my-posh" = "latest"
"ubi:so-fancy/diff-so-fancy" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
